version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Hamilton$29Seven
      POSTGRES_DB: family_meal_planner
    ports:
      - "5432:5432"
  backend:
    build:
      context: .
    volumes:
      - .:/workspace
    command: sleep infinity   # we'll start uvicorn manually
    depends_on:
      - db
    ports:
      - "8002:8002"